In [7]:
import torch
import os

In [5]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

In [60]:
data_path = 'data/train'

data = torch.load(os.path.join(data_path, 'Track00001.pt'))

In [31]:
lenght = data['mix'].shape[1]
C = 2
L  = 129

In [27]:
torch.max(torch.randint(0, lenght, (100*lenght,)))

tensor(83224)

In [61]:
data['mix'] = torch.view_as_real(data['mix'])

In [81]:
te = torch.randint(0, lenght, (100,))

In [93]:
amount = 100

In [107]:
dat = torch.zeros(amount,L,2*C+1,2, dtype=torch.float64)

In [110]:
dat[0]

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        ...,

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]], dtype=torch.float64)

In [113]:
data['mix'][:, 0:5].shape

torch.Size([129, 5, 2])

In [114]:
for j, rand in enumerate(torch.randint(0, lenght, (amount,))):
    if rand < C:
        dat[j][0] = torch.zeros(L, 2)
        i = 1
        while rand-C+i < 0:
            dat[j][i] = torch.zeros(L, 2)
            i+=1
        dat[j][i:] = data['mix'][:, rand-C+i:rand+C+1]
    elif rand > lenght-1-C:
        dat[j][-1] = torch.zeros(L, 2)
        i = 1
        while rand+C-i > lenght-1:
            dat[j][-1-i] = torch.zeros(L, 2)
            i+=1
        dat[j][:-1-i] = data['mix'][:, rand-C:rand+C+1-i]
    else:
        dat[j] = data['mix'][:, rand-C:rand+C+1]

In [116]:
dat[0]

tensor([[[-2.2473e-02,  0.0000e+00],
         [ 3.2042e-02,  0.0000e+00],
         [ 4.0237e-02,  0.0000e+00],
         [-5.1505e-02,  0.0000e+00],
         [-1.1132e-02,  0.0000e+00]],

        [[ 2.8155e-02, -4.5426e-02],
         [-4.7901e-02, -1.2384e-02],
         [-5.2219e-02,  1.2561e-03],
         [ 5.6499e-02,  2.9482e-02],
         [ 1.3143e-02, -3.0081e-02]],

        [[-1.6968e-02,  2.8935e-02],
         [ 4.8454e-02,  4.0656e-02],
         [ 4.6463e-02, -1.0584e-02],
         [-5.0897e-02, -1.4972e-02],
         [-5.6129e-03,  9.1058e-03]],

        ...,

        [[ 7.8259e-06,  3.2129e-05],
         [ 3.7837e-05,  2.4257e-05],
         [ 2.8913e-05, -3.0801e-05],
         [-1.0654e-05, -2.1798e-05],
         [-2.4509e-06,  2.0197e-06]],

        [[-1.5467e-05, -1.8384e-05],
         [-3.3009e-05, -5.9764e-06],
         [-1.4563e-05,  1.8200e-05],
         [ 6.0666e-06,  1.1077e-05],
         [ 1.0658e-05, -1.2810e-05]],

        [[ 2.1092e-05,  0.0000e+00],
         [ 3.9

In [45]:
data['mix'][:, -C:C+1]

tensor([], device='cuda:0', size=(129, 0, 2), dtype=torch.float64)

In [37]:
torch.zeros(2*C+1, L,2, dtype=torch.float64)

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.],
         ...,
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         ...,
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         ...,
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         ...,
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         ...,
         [0., 0.],
         [0., 0.],
         [0., 0.]]], dtype=torch.float64)

In [83]:
torch.view_as_complex(dat)

tensor([[-3.5916e-03+0.0000e+00j,  6.8113e-03+0.0000e+00j,
          3.7434e-03+0.0000e+00j, -3.9418e-03+0.0000e+00j,
         -3.9735e-03+0.0000e+00j],
        [-6.7628e-03-4.4492e-03j, -1.7012e-02+1.6754e-03j,
         -3.7166e-03+2.2813e-02j,  1.5723e-02+2.1996e-02j,
          1.2856e-02+1.1015e-02j],
        [ 1.6004e-02+7.9481e-03j,  2.1101e-02+1.4410e-04j,
         -5.4082e-03-3.1086e-02j, -2.2118e-02-3.4735e-02j,
         -2.2789e-02-3.4928e-02j],
        [-1.1200e-02-7.4109e-03j, -1.8125e-02-1.3004e-02j,
          1.2086e-02+8.4998e-03j,  2.2813e-03+1.7335e-02j,
          3.7046e-03+3.2470e-02j],
        [ 1.8519e-02-7.0890e-03j,  2.5502e-02+3.0573e-02j,
         -1.7752e-02+1.4882e-02j,  3.7082e-03-2.2676e-02j,
          3.1680e-02-1.8898e-02j],
        [-1.5780e-02+1.4651e-02j, -1.5388e-02-2.8278e-02j,
          1.9148e-02-2.2044e-02j,  4.0376e-03+2.0258e-02j,
         -3.5710e-02+8.0636e-03j],
        [-5.6011e-03+4.9638e-03j, -1.9955e-03+2.2763e-03j,
          2.6802e-03+2.

In [87]:
data['mix'][:, te[-1]]

tensor([[ 3.7434e-03,  0.0000e+00],
        [-3.7166e-03,  2.2813e-02],
        [-5.4082e-03, -3.1086e-02],
        [ 1.2086e-02,  8.4998e-03],
        [-1.7752e-02,  1.4882e-02],
        [ 1.9148e-02, -2.2044e-02],
        [ 2.6802e-03,  2.2476e-02],
        [-1.5308e-02, -1.5503e-02],
        [ 6.8679e-03,  6.2789e-04],
        [-1.6555e-05,  6.7920e-03],
        [-7.0278e-04, -4.7274e-03],
        [ 1.8869e-03,  3.4799e-03],
        [-3.5848e-03, -2.2430e-03],
        [ 4.0015e-03,  6.1714e-04],
        [-1.2642e-03, -6.4363e-04],
        [-2.3562e-03,  2.0405e-03],
        [ 1.0471e-03, -2.4542e-03],
        [-1.3517e-03,  2.2246e-05],
        [ 2.7152e-03,  1.7312e-03],
        [ 8.0966e-04, -7.5441e-04],
        [-9.0505e-04, -9.0415e-04],
        [-1.4256e-03,  5.7576e-04],
        [-4.0541e-04,  3.1455e-03],
        [ 1.5698e-03, -5.8723e-03],
        [ 3.1046e-05,  3.9548e-03],
        [-2.9886e-04, -1.6878e-03],
        [-5.9862e-04,  9.7249e-04],
        [ 8.1038e-04, -1.264

In [62]:
data['mix'][:, 83225-1-C:83225-1+C+1-i].shape

torch.Size([129, 3, 2])

In [52]:
lenght

83225

In [73]:
dat = data['mix'][:, 1000-C:1000+C+1]